fun main() {
    try {
        aToZ()
    } catch (e: Exception) {
        println(e.message)
    }
}
